name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to VPS via SSH
      env:
        SSHPASS: ${{ secrets.VPS_PASSWORD }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd ~/project-plus
          git pull origin main  # <-- This pulls the latest code from GitHub
          docker-compose -f docker/docker-compose.yml down
          docker-compose -f docker/docker-compose.yml up -d --build
        EOF
