name: Smart Deploy to VPS

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'docker/**'

jobs:
  deploy-frontend:
    if: ${{ github.event.head_commit.message != 'skip frontend' }}
    runs-on: ubuntu-latest
    name: Deploy Frontend
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy frontend via SSH
        env:
          SSHPASS: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ~/project-plus
            git pull origin main
            docker compose -f docker/docker-compose.yml build frontend-server
            docker compose -f docker/docker-compose.yml up -d frontend-server
          EOF

  deploy-backend:
    if: ${{ github.event.head_commit.message != 'skip backend' }}
    runs-on: ubuntu-latest
    name: Deploy Backend
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy backend via SSH
        env:
          SSHPASS: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ~/project-plus
            git pull origin main
            docker compose -f docker/docker-compose.yml build backend-server
            docker compose -f docker/docker-compose.yml up -d backend-server
          EOF
